CREATE TABLE TB_USER (
 USER_ID NUMBER(10),
 REGI_DT DATE,
 REGMN_ID NUMBER(10),
 CHG_DT DATE,
 CHGMN_ID NUMBER(10)
);

ALTER TABLE TB_USER
ADD CONSTRAINTS PK_TB_USER
PRIMARY KEY (USER_ID);

CREATE TABLE TB_CHATROOM (
 ROOM_ID VARCHAR2(10),
 JOIN_CNT NUMBER(10),
 REGI_DT DATE,
 REGMN_ID NUMBER(10),
 CHG_DT DATE,
 CHGMN_ID NUMBER(10)
);

ALTER TABLE TB_CHATROOM
ADD CONSTRAINTS PK_TB_CHATROOM
PRIMARY KEY (ROOM_ID);

CREATE TABLE TB_CHATROOM_USER (
 ROOM_ID VARCHAR2(10),
 USER_ID NUMBER(10),
 REGI_DT DATE,
 REGMN_ID NUMBER(10),
 CHG_DT DATE,
 CHGMN_ID NUMBER(10)
);

ALTER TABLE TB_CHATROOM_USER
ADD CONSTRAINTS PK_TB_CHATROOM_USER
PRIMARY KEY (ROOM_ID, USER_ID);

CREATE TABLE TB_USER_ACCOUNT (
 USER_ID NUMBER(10),
 BANK_CODE VARCHAR2(2),
 ACCOUNT_NO VARCHAR2(20),
 HOLD_AMT NUMBER(20),
 REGI_DT DATE,
 REGMN_ID NUMBER(10),
 CHG_DT DATE,
 CHGMN_ID NUMBER(10)
);

ALTER TABLE TB_USER_ACCOUNT
ADD CONSTRAINTS PK_TB_USER_ACCOUNT
PRIMARY KEY (USER_ID);


CREATE TABLE TB_THROW_MONEY (
 THROW_ID NUMBER(10),
 THROW_USER_ID NUMBER(10),
 ROOM_ID VARCHAR2(10),
 THROW_AMT NUMBER(20),
 REMAIN_AMT NUMBER(20),
 THROW_NUM NUMBER(10),
 THROW_TOKEN VARCHAR2(3),
 CNCL_YN VARCHAR2(1),
 REGI_DT DATE,
 REGMN_ID NUMBER(10),
 CHG_DT DATE,
 CHGMN_ID NUMBER(10)
);

ALTER TABLE TB_THROW_MONEY
ADD CONSTRAINTS PK_TB_THROW_MONEY
PRIMARY KEY (THROW_ID);


CREATE TABLE TB_GET_MONEY (
THROW_ID	NUMBER(10,0),
GET_SEQ	NUMBER(10,0),
GET_USER_ID	NUMBER(10,0),
GET_DT DATE,
GET_AMT	NUMBER(20,0),
REGI_DT	DATE,
REGMN_ID	NUMBER(10,0),
CHG_DT	DATE,
CHGMN_ID	NUMBER(10,0)
);

ALTER TABLE TB_GET_MONEY
ADD CONSTRAINTS PK_TB_GET_MONEY
PRIMARY KEY (THROW_ID, GET_SEQ);

CREATE SEQUENCE SQ_THROW_ID
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 9999999999
NOCYCLE
NOCACHE;